apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeuser
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeuser
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeuser
  template:
    metadata:
      labels:
        app: kubeuser
    spec: 
      containers:
        - name: kubecontainer
          image: cachu22/dockeroperation:1.0.0
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb+srv://ladrianfer87:u7p7QfTyYPoBhL9j@cluster0.8itfk8g.mongodb.net/ecommerce?retryWrites=true&w=majority&appName=Cluster0"
          imagePullPolicy: Always