openapi: 3.0.1
info:
  title: API para Productos
  description: API para manejar productos en la ecommerce
  version: 1.0.0
paths:
  /api/mgProducts/:
    get:
      summary: Obtiene todos los productos
      tags: 
        - Productos
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Productos obtenidos correctamente de la base de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductArray'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

    post: 
      summary: Crea un producto
      tags: 
        - Productos
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: Producto creado correctamente en la base de datos
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

  /api/mgProducts/products/:
    get: 
      summary: Obtiene todos los productos paginados
      tags: 
        - Productos
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Productos obtenidos correctamente de la base de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductArray'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

  /api/mgProducts/products/category/{category}/:
    get: 
      summary: Obtiene los productos por categoría
      tags: 
        - Productos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: category
          schema:
            type: string
          required: true
          description: La categoría de los productos
      responses:
        "200":
          description: Productos obtenidos correctamente de la base de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductArray'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

  /api/mgProducts/products/status/{availability}/:
    get: 
      summary: Obtiene los productos por disponibilidad
      tags: 
        - Productos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: availability
          schema:
            type: string
          required: true
          description: La disponibilidad de los productos
      responses:
        "200":
          description: Productos obtenidos correctamente de la base de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductArray'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

  /api/mgProducts/products/sort/{sortByPrice}/{order}:
    get:
      summary: Obtener productos ordenados por precio
      tags:
        - Productos
      parameters:
        - in: path
          name: sortByPrice
          required: true
          schema:
            type: string
            enum: [price]
          description: El campo por el cual ordenar los productos (actualmente solo 'price' está soportado)
        - in: path
          name: order
          required: true
          schema:
            type: string
            enum: [asc, desc]
          description: El orden en el cual ordenar los productos ('asc' para ascendente, 'desc' para descendente)
      responses:
        "200":
          description: Productos ordenados correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        "400":
          description: Parámetros de ordenamiento no válidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Parámetros de ordenamiento no válidos
        "500":
          description: Error al obtener productos ordenados por precio
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Error al obtener productos ordenados por precio

  /api/mgProducts/{pid}/:
    get: 
      summary: Obtiene un producto por su ID
      tags: 
        - Producto
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: El ID del producto
      responses:
        "200":
          description: Producto obtenido correctamente de la base de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

    put:
      summary: Modifica un producto
      tags: 
        - Producto
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: El ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: Producto modificado correctamente en la base de datos
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

    delete:
      summary: Elimina un producto
      tags: 
        - Producto
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: El ID del producto
      responses:
        "200":
          description: Producto eliminado correctamente de la base de datos
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la app

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID autogenerado de Mongo
        name:
          type: string
          description: Nombre del producto
        category:
          type: string
          description: Categoría del producto
        availability:
          type: string
          description: Disponibilidad del producto
        price:
          type: number
          description: Precio del producto
      example:
        _id: "60c72b2f9b1e8b3f8b2f8b3f"
        name: "Producto de ejemplo"
        category: "Categoría de ejemplo"
        availability: "Disponible"
        price: 100.0
    ProductArray:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID autogenerado de Mongo
        products:
          type: array
          items:
            type: object
            properties:
              product:
                $ref: '#/components/schemas/Product'
              quantity:
                type: integer
                description: Cantidad del producto en el carrito
      example:
        _id: "60c72b2f9b1e8b3f8b2f8b3f"
        products: 
          - product: 
              _id: "60c72b2f9b1e8b3f8b2f8b3f"
              name: "Producto de ejemplo"
              category: "Categoría de ejemplo"
              availability: "Disponible"
              price: 100.0
            quantity: 5